### ISSUE TITLE
Unexpected Keyword Argument 'Diffusion'

### ISSUE THREAD

**Issue by Quantium0** [Zhendong-Wang/Diffusion-GAN#8]
Hey there,
I stumbled upon this project when I was studying different types of GANS.
I ran train.py on my own dataset,
everything worked out, until right after the networks finished loading in, it gave me the error
"TypeError: __init__() got an unexpected keyword argument 'Diffusion'"
do you have any idea how I could fix this

The error happened during "setting up training phases..."
Thanks

Full Error:

`Traceback (most recent call last):
  File "train.py", line 531, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/quantium/anaconda3/envs/stylegan2-ada/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/quantium/anaconda3/envs/stylegan2-ada/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/quantium/anaconda3/envs/stylegan2-ada/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/quantium/anaconda3/envs/stylegan2-ada/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/quantium/anaconda3/envs/stylegan2-ada/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 524, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 357, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/mnt/c/Users/quant/DGAN/diffusion-stylegan2/training/training_loop.py", line 213, in training_loop
    loss = dnnlib.util.construct_class_by_name(device=device, **ddp_modules, **loss_kwargs) # subclass of training.loss.Loss
  File "/mnt/c/Users/quant/DGAN/diffusion-stylegan2/dnnlib/util.py", line 289, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
  File "/mnt/c/Users/quant/DGAN/diffusion-stylegan2/dnnlib/util.py", line 284, in call_func_by_name
    return func_obj(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'Diffusion'`

**Comment by starsong98** [comment]
I am also having the same issue.
Does anybody know why this is happening?

**Comment by Zhendong-Wang** [comment]
Hi there, sorry the bug was because I occasionally changed the diffusion module name from 'diffusion' to 'Diffusion'. I have fixed the bug. You could git pull and train your model. 

Thanks,

**Comment by starsong98** [comment]
Thank you!
