### ISSUE TITLE
Error when resuming training on Diffusion-StyleGAN2 for CelebA-64 dataset

### ISSUE THREAD

**Issue by starsong98** [Zhendong-Wang/Diffusion-GAN#9]
Hello,
I am trying to resume training using the pretrained weights on the CelebA-64 dataset, but I am having problem loading the weights into the model. I am currently using these commands:

python train.py --outdir=[outdir] --data=[data folder] --gpus=1 --cfg auto --kimg 25000 --aug no --target 0.6 --noise_sd 0.05 --ts_dist priority --resume pretrained/diffusion-stylegan2-celeba64.pkl

I am getting the following error message:
```
Constructing networks...
Setting up augmentation...
Resuming from "pretrained/diffusion-stylegan2-celeba64.pkl"
Traceback (most recent call last):
  File "train.py", line 531, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 524, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 357, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "Diffusion-GAN-main/diffusion-stylegan2/training/training_loop.py", line 180, in training_loop
    misc.copy_params_and_buffers(resume_data[name], module, require_all=False)
  File "Diffusion-GAN-main/diffusion-stylegan2/torch_utils/misc.py", line 160, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (256) must match the size of tensor b (512) at non-singleton dimension 0
```
I believe this may have something to do with mismatching channel dimensions. How can I fix these?

**Comment by Zhendong-Wang** [comment]
Hi starsong98, I just tried on my end. The checkpoint works well and could be resumed for further training. Do you make sure that your CelebA is 64x64 resolution?

**Comment by starsong98** [comment]
I checked just now, it is indeed 64 x 64 resolution.
I think the model architecture just does not match, but I could be wrong.

**Comment by starsong98** [comment]
Thank you! Your command did the trick. Looks like it was some of the other arguments instead that were interfering.

But now the "Evaluating metrics..." part is taking really long for some reason. Could it be because I do not have Tensorboard installed in that environment?

**Comment by Zhendong-Wang** [comment]
Emmm, Tensorboard should not impact the evaluation time. Pytorch version could sometimes matter. Usually the first evaluation could take longer for set up evaluation stage, but the later ones will be faster.

**Comment by starsong98** [comment]
I seem to have gotten a sort of time out error message:
```
Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 528, in main
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(args, temp_dir), nprocs=args.num_gpus)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "Documents/ai504/project1/Diffusion-GAN-main/diffusion-stylegan2/train.py", line 359, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "Documents/ai504/project1/Diffusion-GAN-main/diffusion-stylegan2/training/training_loop.py", line 437, in training_loop
    value = phase.start_event.elapsed_time(phase.end_event)
  File "anaconda3/envs/diffusiongan2/lib/python3.7/site-packages/torch/cuda/streams.py", line 177, in elapsed_time
    return super(Event, self).elapsed_time(end_event)
RuntimeError: Both events must be recorded before calculating elapsed time.
```

Does this mean that it took too long to compute the metrics?

**Comment by Zhendong-Wang** [comment]
NO, this is because your ``--kimg`` is smaller than the kimg has been trained. You should be able to know how many images trained from the first line output after training starts. ``kimg`` represents that the total numbers images will be trained. 

The current resuming record the number of images trained. But you modify this to make it forget it. Then the ``kimg`` will be the number of images futher trained.

**Comment by starsong98** [comment]
I see. Thank you.

**Comment by aaaapineapple** [comment]
> NO, this is because your `--kimg` is smaller than the kimg has been trained. You should be able to know how many images trained from the first line output after training starts. `kimg` represents that the total numbers images will be trained.
> 
> The current resuming records the number of images trained. But you can modify this to make it forget it. Then the `kimg` will be the number of images futher trained.

hello!
Should I modify the value of kimg or do I need to do some processing，

**Comment by aaaapineapple** [comment]
@starsong98  May I ask how you resolved it？

**Comment by menyouhua1** [comment]
@aaaapineapple Hello,have you solved the problem?

**Comment by Jiangshouyu1** [comment]
@menyouhua1 Hello, i meet the same problem, have you solved it?

**Comment by Jiangshouyu1** [comment]
@aaaapineapple Hello, i meet the same problem, have you solved it?
